runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: /(.*\.(css|js))
  static_files: __static__/\1
  upload: __static__/(.*)
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /upload
  script: unused
  login: optional
  secure: optional
- url: /serve
  script: unused
  login: optional
  secure: optional
- url: /blobstore-upload-url
  script: unused
  login: optional
  secure: optional
- url: /(.*)
  static_files: __static__/index.html
  upload: __static__/index.html
  secure: always

skip_files: app.yaml
